// countries
export const SET_COUNTRIES = "SET_COUNTRIES"
export const RESET_COUNTRIES = "RESET_COUNTRIES"
export const SET_COUNTRY_NAME = "SET_COUNTRY_NAME"
export const SET_COUNTRY_CODE = "SET_COUNTRY_CODE"
export const TOGGLE_FULL_NAME = "TOGGLE_FULL_NAME"
export const DISPLAY_NETWORK_ERROR = "DISPLAY_NETWORK_ERROR"
export const HIDE_NETWORK_ERROR = "HIDE_NETWORK_ERROR"
